### ISSUE TITLE
Name the bot more respectfully

### ISSUE THREAD

**Issue by svg1007** [avvero/average-thirty-seven-years-old-man-bot#8]
**Problem**: the current name of the bot in telegram is "поебот" which does sound disrespectfully

**Solution**: As long as all the members of the chat are mature let's call the bot more respectfully. Let's change his name to start with a capital letter - "Поебот"

**DoD**: The bot in the chat has the name "Поебот"

**Comment by avvero** [comment]
It would take 5sp at least, let's plan for the next sprint

**Comment by avvero** [comment]
Is not considered to be a bug

**Comment by avvero** [comment]
Fixed
